module.exports = {
  content: {
    relative: true,
    files: ["../index.html"],
  },
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#1e1f25",
        "inverse-primary": "#005fad",
        "on-tertiary": "#482900",
        "background": "#111318",
        "surface-tint": "#a4c9ff",
        "on-tertiary-container": "#4d2c00",
        "surface-container-low": "#1a1b21",
        "on-primary-fixed-variant": "#004884",
        "on-error": "#690005",
        "on-primary": "#00315d",
        "on-secondary-fixed": "#191c22",
        "outline": "#8a919e",
        "secondary-container": "#44474f",
        "surface-dim": "#111318",
        "tertiary-fixed": "#ffdcbb",
        "surface": "#111318",
        "on-secondary-container": "#b3b5be",
        "on-tertiary-fixed": "#2c1700",
        "on-surface-variant": "#c0c7d4",
        "error-container": "#93000a",
        "on-primary-fixed": "#001c39",
        "error": "#ffb4ab",
        "on-secondary": "#2d3038",
        "on-surface": "#e2e2e9",
        "surface-bright": "#37393f",
        "on-tertiary-fixed-variant": "#683d00",
        "tertiary-fixed-dim": "#ffb869",
        "tertiary-container": "#de8800",
        "primary-container": "#4a9eff",
        "inverse-surface": "#e2e2e9",
        "surface-variant": "#33353a",
        "secondary-fixed-dim": "#c4c6d0",
        "tertiary": "#ffb869",
        "on-secondary-fixed-variant": "#44474f",
        "surface-container-highest": "#33353a",
        "secondary": "#c4c6d0",
        "primary-fixed": "#d4e3ff",
        "secondary-fixed": "#e0e2ec",
        "surface-container-high": "#282a2f",
        "inverse-on-surface": "#2e3036",
        "surface-container-lowest": "#0c0e13",
        "on-background": "#e2e2e9",
        "on-primary-container": "#003463",
        "primary": "#a4c9ff",
        "on-error-container": "#ffdad6",
        "outline-variant": "#414752",
        "primary-fixed-dim": "#a4c9ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["Inter"],
        label: ["Inter"],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
